Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,7 +3,7 @@ name: Increment Version Number
 on:
   push:
     branches:
-      - master
+      - main
 
 jobs:
   increment_version_number:
@@ -14,8 +14,13 @@ jobs:
       - name: Increment version number
         run: |
           VERSION=$(cat version.txt)
-          NEW_VERSION=$((VERSION+1))
-          echo $NEW_VERSION > version.txt
+          if [[ "$VERSION" =~ ^[0-9]+$ ]]; then
+            NEW_VERSION=$((VERSION+1))
+            echo $NEW_VERSION > version.txt
+          else
+            echo "Error: version.txt does not contain a valid version number"
+            exit 1
+          fi
       - name: Commit changes
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
